version: '3'

services:
  postgres:
    image: 'postgres:14.4'
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: joshua
      POSTGRES_PASSWORD: capitalX123
      POSTGRES_DB: concurrency
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./db-data/redis/:/data

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always