version: '3.1'

services:
  mongo:
    image: mongo
    container_name: docker_mdb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: joshua
      MONGO_INITDB_ROOT_PASSWORD: capitalX123

  mongo-express:
    image: mongo-express
    container_name: docker_me
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: joshua
      ME_CONFIG_MONGODB_ADMINPASSWORD: capitalX123
      ME_CONFIG_MONGODB_URL: mongodb://joshua:capitalX123@mongo:27017/